server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  type-aliases-package: com.guomei.pojo
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  application:
    #微服务名
    name: users-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guomei
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:6001/eureka


